### PR TITLE
changed search url to serve up #javascript tweet hashtag also

### PR DESCRIPTION
**Pull request by Oghenebrume50**
This makes it serve more tweets and the one for 2nd July also. With the #javascript we could get tweet we do not need also, but we can also clean that up with a search for keywords like **challenge**, **lesson** and **class** in the tweet.

### CODE REVIEW

**Comment by Oghenebrume50** [comment]
For now, the content we get is fine, I checkedout the repl.it link you sent I feel that will require manually putting those content up in the API, I don't think we can scrap content of repl.it, worse how do we avoid duplicates

**Comment by Oghenebrume50** [comment]
**Bullet points of all I did**
- Removed the `end date` from the search string, because it works with timezone, I observed it in the last post, when Jchaitt made it, it didn't show up until I removed it.
- sorted the api output with the date in descending order. I just noticed the current output comes out as sorted but this doesn't happen in my local environment, maybe an overkill.
- Added tags query to support array,prototype and scope, either or a combination of any 
Below is the output of some of the query.
array
Prototype
scope
protoscope
nocontent

**Comment by Oghenebrume50** [comment]
@mtliendo Please review so I know if I am on track or not.

**Comment by mtliendo** [comment]
This is awesome work, thanks so much. In this case, how would someone go about receiving all the challenges, regardless of tags? The last screenshot you posted looks like nothing gets returned.

**Comment by Oghenebrume50** [comment]
> This is awesome work, thanks so much. In this case, how would someone go about receiving all the challenges, regardless of tags? The last screenshot you posted looks like nothing gets returned.

Hi, I left that as it was before now, the last screenshot shows when someone does not pass a value to the tags query key. maybe I should change the url to be similar that is like this

- get all contents: /jcsjs-lessons
- get content based on tags: /jcsjs-lessons?tags=parameters

**Comment by mtliendo** [comment]
> get all contents: /jcsjs-lessons
get content based on tags: /jcsjs-lessons?tags=parameters

That sounds like a plan.  If you don't mind pushing that commit up and I'll go ahead and merge.  Thanks again for all your work on this!

**Comment by Oghenebrume50** [comment]
You are welcome, I am just determined to improve my skills and open source experience. It is done, the uri is /jcsjs-lessons we may need to add this to the readme file, and maybe how to use the supported tags too

**Comment by mtliendo** [comment]
PR is merged.  I'll push to the server later on today

**Pull request merged**
